# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
