# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181006_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='latitud',
            field=models.FloatField(default=-74.064908, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='longitud',
            field=models.FloatField(default=4.602908, max_length=8),
            preserve_default=False,
        ),
    ]
